Dev (#1)
* add to readme

* building out tests

* updated test docs

* more changes to docs

* updated factorial code

* added MCPs

* updated docs

* added CCD designs

* cleaning up

* updated naming

* updating docs

* added taguchi

* added hashing anf MCPs

* adding in code from long ago

* removing idea folder

* adding idea to ignore file

* adding tests

* cleaning up tests

* cleaning up tests

* added randomization checks

Co-authored-by: smarmy-parity <drjohm@gmail.com>
Co-authored-by: James-Montgomery <looyclark@gmail.com>

diff --git a/docs/Makefile b/docs/Makefile
--- a/docs/Makefile
+++ b/docs/Makefile
@@ -17,7 +17,17 @@ help:
 # Catch-all target: route all unknown targets to Sphinx using the new
 # "make mode" option.  $(O) is meant as a shortcut for $(SPHINXOPTS).
 %: Makefile
-	cd .. && pip install .
-	sphinx-apidoc -f -o source/ ../project_name
-	#sphinx-build -b coverage . build/coverage
+	echo --- Install local package with tests in editable mode . . .
+	cd .. && pip -q install -e .["tests"] # must install as  editable for autodocs to work
+	echo --- Run package tests and generate coverage report . . .
+	cd .. && pytest
+	echo --- Run package style checks and generate style report . . .
+	cd .. && pylint -f text lind > ./docs/style/pylint_report.txt || echo "required to avoid makefile error"
+	echo --- Run autodoc to update package documentation . . .
+	sphinx-apidoc -f -o source/ ../lind
+	echo --- Run documentation coverage rport . . .
+	sphinx-build -b coverage . build/coverage
+	echo --- logging current git tag . . .
+	git describe --tags > ./latest_tag.txt
+	echo --- Make documentation . . .
 	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
